# Generated by Django 3.0.5 on 2022-03-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220321_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='FutsalName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='yWEQZ', max_length=5),
        ),
        migrations.AlterField(
            model_name='ground',
            name='code',
            field=models.CharField(default='yWEQZ', max_length=5),
        ),
    ]
